# Generated by Django 3.0.5 on 2020-07-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
