# Generated by Django 3.0.5 on 2020-07-19 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0003_auto_20200719_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
