# Generated by Django 3.0.5 on 2020-07-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0005_auto_20200719_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phon',
            field=models.CharField(default='+2126', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialist',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
