# Generated by Django 3.0.5 on 2020-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0006_auto_20200719_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='doc.jpg', upload_to='./images'),
        ),
    ]
