# Generated by Django 3.0.5 on 2020-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0007_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
