# Generated by Django 3.0.5 on 2020-07-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0008_profile_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-price',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slag',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phon',
            field=models.CharField(default='+2126', max_length=13),
        ),
    ]
