# Generated by Django 3.0.5 on 2020-07-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0009_auto_20200720_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slag',
            new_name='slug',
        ),
    ]
