# Generated by Django 3.0.5 on 2020-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0010_auto_20200720_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
