# Generated by Django 3.0.5 on 2020-07-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0012_profile_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, choices=[('a', 'eyes Doctor'), ('a', 'Physiologist'), ('a', 'Dentist'), ('a', 'psychologist')], max_length=30, null=True),
        ),
    ]
