# Generated by Django 3.0.5 on 2020-07-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabib', '0014_auto_20200720_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, choices=[('a', 'Physiologist'), ('a', 'psychologist'), ('a', 'Dentist'), ('a', 'eyes Doctor')], max_length=30, null=True),
        ),
    ]
